# Generated by Django 3.2.16 on 2023-01-22 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_blog', '0002_auto_20230113_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
