# Generated by Django 3.2.16 on 2023-01-25 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_learningcategory'),
        ('flow_blog', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.learningcategory'),
        ),
    ]
