# Generated by Django 3.2.16 on 2023-01-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningCategory',
        ),
    ]
