# Generated by Django 3.2.16 on 2023-01-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_learningcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcategory',
            name='start_quote',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
