# Generated by Django 3.2.16 on 2023-02-10 18:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_learningcategory_importance_of_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcategory',
            name='category_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
