# Generated by Django 3.2.16 on 2022-12-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
