# Generated by Django 3.2.16 on 2022-12-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusers', '0002_auto_20221223_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
