# Generated by Django 3.2.16 on 2023-01-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusers', '0003_profile_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedIn_url',
            field=models.URLField(default='https://www.linkedin.com/', max_length=100),
        ),
    ]
