# Generated by Django 3.2.16 on 2023-01-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteusers', '0005_profile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
    ]
