# Generated by Django 3.2.16 on 2023-01-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_learningcategory'),
        ('siteusers', '0006_remove_profile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(related_name='user_learning_categoy', to='categories.LearningCategory'),
        ),
    ]
